# Generated by Django 3.2 on 2022-09-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('Mobile', models.IntegerField(verbose_name='Mobile Number')),
                ('Msg', models.TextField(max_length=400, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CV', models.FileField(max_length=400, upload_to=None, verbose_name='Resume')),
            ],
        ),
    ]
